# Generated by Django 5.1.1 on 2024-09-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnreadMessage',
            new_name='PerformanceMarketingGroupMessaages',
        ),
    ]
